<template>
  <div class="content">
    <div class="row">
      <div class="image-emoji">
        <img
          src="../assets/emoji_1.jpg"
          alt="emoji"
          class="bordered-image"
        />
      </div>

      <div><EmojiCloud /></div>

    </div>

    <div class="row">
      <div class="text-intro bordered-div">
        <h1>Social media has become one of the most frequently used tools for human communication. 
        In 2019, there were already 7.7 billion people who use social media and regarded it as an 
        important tool in daily life.</h1>
        <h1>For the large number of posts which were generated by the 
        usage of people across the world, the emojis within the posts have shown to have some 
        important linguistic function in conversations.</h1>
      </div>

      <div class="aim bordered-div">
        <h1>Our aim</h1>
        <h2> - To explore the twitter tweets and Mastodon toots that were posted within Australia 
        from many perspectives. </h2>
        <h2> - Focus on the emojis within the posts by considering sentiment and some other 
        geology-based data as the factors. </h2>
      </div>

      <div class="task bordered-div">
        <h1>What did we do</h1>
        <h2>To analyse the emoji data with the social media posts, a Cloud-based system 
        that utilises virtual machines on the UniMelb Research Cloud for harvesting 
        and processing Mastodon toots and Twitter tweets has been implemented. 
        This system harvest, preprocess, and stores the social media data into CouchDb database. 
        Based on the harvest social media data, a range of analytic scenarios such as discovering 
        the most frequently used emoji for different sentiment posts or the most frequently used 
        emoji in different great capital cities has been analysed, and these analytics eventually 
        were visualised with a front-end web application.</h2>
      </div>
    </div>
  </div>
</template>

<script>
import EmojiCloud from './graph/EmojiCloud.vue';

export default {
  name: "HomePage",
  components: {
    EmojiCloud,
  },
};
</script>

<style scoped>
.content {
  flex-direction: column;
  align-items: center;
  display: flex;
  margin-left: 160px;
  margin-bottom: 20px;
  padding: 3rem;
}

.image-emoji {
  text-align: center;
  padding-bottom: 5rem;
  margin-left: 240px;
}

.bordered-image {
  border: 1px solid #ccc;
  border-radius: 50%;
  max-width: 800px;
}

.row {
  justify-content: space-between;
  display: flex;
  margin: 2rem 0;
  width: 100%;
}

.bordered-div {
  justify-content: space-around;
  border: 1px solid #ccc;
  flex-direction: column;
  display: flex;
  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
  border-radius: 10px;
  margin-top: -100px;
  margin-right: 30px;
  margin-left: 30px;
  min-height: 200px;
  padding: 2rem;
  flex: 1;
}

.text-intro h1{
  font-family: 'Alegreya', serif;
  text-align: center;
  font-size: 22px;
}

.aim h1 {
  font-family: 'Alegreya', serif;
  text-align: center;
  font-size: 22px;
}

.task h1 {
  font-family: 'Alegreya', serif;
  text-align: center;
  font-size: 22px;
}

.aim h2 {
  font-family: 'Alegreya', serif;
  text-align: justify;
  font-size: 18px;
}

.task h2 {
  font-family: 'Alegreya', serif;
  text-align: justify;
  font-size: 18px;
}

.aim h1 {
  font-size: 30px;
}

.task h1 {
  font-size: 30px;
}
</style>
